sudo: required
dist: trusty
matrix:
  include:
  - language: node_js
    node_js:
    - "11.10.1"
    before_install:
    - cd static/src && ls
    install:
    - TASK_PRESENTER_VERSION=$(node -p "require('./package.json').devDependencies['@dtwebservices/task-presenter-components']")
    - npm install https://s3.amazonaws.com/cf-s3uploads/pybv/${TASK_PRESENTER_VERSION}/task-presenter-components.tgz
    - yarn install
    - ls ./node_modules
    - yarn test
    - yarn lint
